name: foxtrail-ai
services:
  - name: backend
    source_dir: backend
    environment_slug: python
    instance_size_slug: basic-xxs
    github:
      branch: main
      deploy_on_push: true
      repo: arethefreshest/foxtrail
    dockerfile_path: backend/Dockerfile
    http_port: 8080
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${REDIS_URL}
      - key: SECRET_KEY
        scope: RUN_TIME
        value: ${SECRET_KEY}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        value: ${OPENAI_API_KEY}
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${APP_URL}
      
  - name: frontend
    source_dir: frontend
    environment_slug: node-js
    instance_size_slug: basic-xxs
    github:
      branch: main
      deploy_on_push: true
      repo: arethefreshest/foxtrail
    dockerfile_path: frontend/Dockerfile
    http_port: 8080
    build_command: npm run build
    run_command: serve -s build -l 8080
    envs:
      - key: REACT_APP_API_URL
        scope: BUILD_TIME
        value: ${API_URL} 